OnlineMobileShop/Controllers/MobileController.cs
using System.Collections.Generic;
using OnlineMobileShop.Entity;
using OnlineMobileShop.Respository;
using System.Web.Mvc;
using System.Data;

namespace OnlineMobileShop.Controllers
{  
    public class MobileController : Controller
    {
        // GET: Mobile
        MobileRespository repository = new MobileRespository();
        public ActionResult RunMaster()
        {
            return View();
        }
        public ActionResult MobileDetails()
        {
            
            DataTable mobile = repository.GetDetails();
            ViewBag.Mobile = mobile;
            ViewData["mobile"] = mobile;
            TempData["mobile"] = mobile;
            return RedirectToAction("DisplayDetails");
        }
        public ActionResult DisplayDetails()
        {
           DataTable mobilelist = repository.GetDetails();
            return View(mobilelist);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create_post(Mobile mobile)
        {
            Mobile mobiles = new Mobile();
            if (ModelState.IsValid)
            {
                mobile.Brand = mobile.Brand;
                mobile.Model = mobile.Model;
                mobile.Battery = mobile.Battery;
                mobile.RAM = mobile.RAM;
                mobile.ROM = mobile.ROM;
                mobile.Price = mobile.Price;
                if(MobileRespository.Add(mobile)>0)
                {
                    ViewBag.message = "Successfull";
                }
                ViewBag.message = "falied";
            }
            return View();
        }
        //[HttpGet]
        //public ActionResult Edit(int id)
        //{
        //    Mobile mobile = MobileRespository.GetMobileID(id);
        //    return View(mobile);
        //}
        //[HttpGet]
        //public ActionResult Delete(int id)
        //{
        //    MobileRespository.Delete(id);
        //    return RedirectToAction("MobileDetails");
        //}
        //[HttpPost]
        //public ActionResult Update()
        //{
        //    Mobile mobile = new Mobile();
        //    TryUpdateModel<Mobile>(mobile);
        //    MobileRespository.Update(mobile);
        //    return RedirectToAction("MobileDetails");


        //}

    }
}

OnlineMobileShop/Controllers/MobilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineMobileShop.Entity;
using OnlineMobileShop.Respository;

namespace OnlineMobileShop.Controllers
{
    public class MobilesController : Controller
    {
        private DBContext db = new DBContext();

        // GET: Mobiles
        public ActionResult Index()
        {
            return View(db.mobile.ToList());
        }

        // GET: Mobiles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mobile mobile = db.mobile.Find(id);
            if (mobile == null)
            {
                return HttpNotFound();
            }
            return View(mobile);
        }

        // GET: Mobiles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Mobiles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MobileID,Brand,Model,Battery,RAM,ROM,Price")] Mobile mobile)
        {
            if (ModelState.IsValid)
            {
                db.mobile.Add(mobile);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(mobile);
        }

        // GET: Mobiles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mobile mobile = db.mobile.Find(id);
            if (mobile == null)
            {
                return HttpNotFound();
            }
            return View(mobile);
        }

        // POST: Mobiles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MobileID,Brand,Model,Battery,RAM,ROM,Price")] Mobile mobile)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mobile).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(mobile);
        }

        // GET: Mobiles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mobile mobile = db.mobile.Find(id);
            if (mobile == null)
            {
                return HttpNotFound();
            }
            return View(mobile);
        }

        // POST: Mobiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Mobile mobile = db.mobile.Find(id);
            db.mobile.Remove(mobile);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineMobileShop/Views/Shared/Master.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
  <body style="height: 59px">
    <div>
        <center>
    <div style="width: 100%;height:50px;background-color:pink">
   
            <span  style="font-size:20px"><h1>  @Html.ActionLink("Welcome To Online Mobile Shop", "Index", "Home")</h1></span>
        
          </div>
        </center>
      @Html.ActionLink("Register", "SignUp", "Account")

      @Html.ActionLink("LogIn", "Login", "Account")

        @Html.ActionLink("DisplayDetails","DisplayDetails","Mobile")

        @Html.ActionLink("DisplayUserDetails","DisplayUserDetails","Account")
    </div>
     <!-- <table style="width: 1100px; margin: auto">
        <tr style="width: 1100px; height: 50px">
          <td style="width: 120px; "><h1 align="center">Welcome To Online Mobile Shop</h1></td>
        </tr>
        <tr style="width: 1100px; height: 40px; background-color:lightblue;color:black">
          <td>
          
          </td>
        </tr>
        <tr style="width: 1100px; height: 20px; text-align:center">
          <td colspan="3">
          
          </td>
        </tr>
      </table>-->
        <div >
                   @RenderBody() 
            </div>

     </body>
</html>

OnlineMobileShop/Views/Shared/_Mobile.cshtml
@{
    ViewBag.Title = "_Mobile";
}


<tr>
    <td> @Model["MobileID"]</td>
    <td> @Model["Brand"]</td>
    <td>@Model["Model"]</td>
    <td>@Model["Battery"]</td>
    <td> @Model["Price"]</td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = Model["MobileID"] })
        @Html.ActionLink("Delete", "Delete", new { id = Model["MobileID"] })
    </td>
</tr>